name: flutter_gpa
description: "A modern GPA calculator app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.5.1
  flutter_animate: ^4.5.0
  fl_chart: ^0.65.0
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
